### ISSUE TITLE
On newly generated, package.json has "grunt-filerev": "^0.2.2", version doesn't exist

### ISSUE THREAD

**Issue by nagey** [aaronallport/generator-angular-require#51] opened 2015-03-04 21:05 UTC
Just got the latest (v0.4.2) of the generator, and on a newly generated app, failing because grunt-filerev ^0.2.2 doesn't exist (latest 0-branch release is 0.2.1)

**Comment by luidroid** [comment] 2015-03-16 13:03
The problem is that the dependencies on package.json are out of date.
I solved this problem by installing npm-check-updates from https://www.npmjs.com/package/npm-check-updates
Steps you take under ../yourAngularRequireProject/ :
1) npm install -g npm-check-updates
2) npm-check-updates -u
3) npm cache clean
4) npm install
5) grunt build

**Comment by argentinaluiz** [comment] 2015-03-28 03:36
Great @luidroid, its works, thanks!

**Comment by bisubus** [comment] 2015-04-09 17:59
Thanks, great. Won't newer dependencies cause any issues? I've solved it by changing `^0.2.2` to `^0.2.1` (I wonder what happened to 0.2.2).

**Comment by luidroid** [comment] 2015-04-09 20:30
It does not cause any issues because the dependencies will be updated and solved according to the existing semantic version policies in the package.json. Your solution @bisubus is also right but I wanted to make it general for all possible cases.

**Comment by brunowego** [comment] 2015-05-09 00:15
@luidroid thanks!

**Comment by aaronallport** [comment] 2015-06-08 20:29
This is resolved in https://github.com/aaronallport/generator-angular-require/releases/tag/v1.0.0

**Closed by aaronallport** 2015-06-08 20:29 UTC
